
CREATE TABLE Log (
LogID INTEGER PRIMARY KEY,
Applikation TEXT NOT NULL,
Level TEXT NOT NULL,
Message TEXT NOT NULL,
Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
Device TEXT,
Exception TEXT,
FOREIGN KEY (Device) REFERENCES Devices(DeviceID)
);