CREATE TABLE ProcessVars (
ProcVarsID INTEGER PRIMARY KEY,
Device INTEGER NOT NULL,
Name TEXT NOT NULL,
Datatype TEXT NOT NULL,
DB TEXT NOT NULL,
Value INTEGER,
Quality INTEGER,
Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(Device) REFERENCES Devices(DeviceID)

);